application: livegatherapi
version: 1
runtime: python
api_version: 1

handlers:
- url: /test.*
  script: gaeunit.py

- url: /(.*\.(html|ico))
  static_files: \1
  upload: (.*\.(html|ico))

- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /js
  static_dir: js

# Callback URL for Blobstore CANNOT be HTTPS
- url: /photos
  script: __init__.py

- url: /.*
  script: __init__.py
#  secure: always
