application: lg
version: 1
runtime: python
api_version: 1

handlers:
- url: /test.*
  script: gaeunit.py

- url: /(.*\.(html|ico))
  static_files: \1
  upload: (.*\.(html|ico))

- url: /.*
  script: lg.py
  secure: always
